version: '3.8'

services:
  trainchecker-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainchecker-frontend
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "90:80"
    # If your frontend needs to communicate with a backend service within the same Docker Compose network,
    # you can add a dependency here. For example:
    # depends_on:
    #   - your-backend-service-name