version: '3.8'

services:
  trainchecker-frontend:
    build:
      context: ../trainchecker-frontend
      dockerfile: Dockerfile
      args:
        VITE_TRAIN_CHECKER_API_BASE_URL: ${VITE_TRAIN_CHECKER_API_BASE_URL}
    container_name: trainchecker-frontend
    restart: unless-stopped
    ports:
      - "90:80"
    env_file:
      - .env
    # If your frontend needs to communicate with a backend service within the same Docker Compose network,
    # you can add a dependency here. For example:
    # depends_on:
    #   - your-backend-service-name